/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_minima_utils_jni_jnifunctions */

#ifndef _Included_org_minima_utils_jni_jnifunctions
#define _Included_org_minima_utils_jni_jnifunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_minima_utils_jni_jnifunctions
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_minima_utils_jni_jnifunctions_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     org_minima_utils_jni_jnifunctions
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_minima_utils_jni_jnifunctions_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_minima_utils_jni_jnifunctions
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_minima_utils_jni_jnifunctions_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_minima_utils_jni_jnifunctions
 * Method:    hashHeader
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_minima_utils_jni_jnifunctions_hashHeader
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_minima_utils_jni_jnifunctions
 * Method:    hashHeaderWithDiff
 * Signature: ([BI[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_minima_utils_jni_jnifunctions_hashHeaderWithDiff
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
