/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.minima.tests;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class AppTest {

    @Test
    public void testAppHasAGreeting() {
        //App classUnderTest = new App();
        assertNotNull("app should have a greeting", 1); // classUnderTest.getGreeting());
    }
}
