#!/bin/sh

# Constants
APP_JAR="minima.jar"
APP_NAME="Minima"

# Set the working directory
DIR=$(cd "$(dirname "$0")"; pwd)
JAR_PATH="$DIR/$APP_JAR"

# Run the application
osascript \
	-e 'tell application "Terminal" 
        do script "java -jar '$JAR_PATH'"
	activate
	end tell'
exit