name: Manual Release
on:
  workflow_dispatch:
    inputs:
      publish_artifacts:
        description: Publish artifact
        type: boolean
        default: false
        required: true
      artifacts_version:
        description: Release artifact version
        default: '0.0.1-test'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - run: echo ${{github.event.inputs.publish_artifacts == 'true'}}
     - uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'adopt'
     - name: Build And Test
       run: ./gradlew clean build
       working-directory: ./
     - name: Publish Artifact
       if: ${{ github.event.inputs.publish_artifacts == 'true'}}
       run: ./gradlew publish
       working-directory: ./
       env:
         USERNAME: ${{ github.actor }}
         TOKEN: ${{ secrets.GITHUB_TOKEN }}
         VERSION: '${{ github.event.inputs.artifacts_version }}'
